# Generated by Django 5.2.8 on 2026-07-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cadastro_rg_ie_cadastro_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacliente',
            options={'permissions': [('acesso_modulo', 'Acesso ao módulo Cadastros')], 'verbose_name': 'Categoria de Cliente', 'verbose_name_plural': 'Categorias de Clientes'},
        ),
    ]
