# Generated by Django 5.2.8 on 2026-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametrosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosistema',
            name='chave',
            field=models.CharField(choices=[('CAIXA_PADRAO_ID', 'Financeiro - ID do Caixa Padrão'), ('TAXA_JUROS_MENSAL', 'Financeiro - Taxa de Juros Mensal (%)'), ('PLANO_CONTAS_MENSALIDADE_ID', 'Financeiro - ID Plano Contas (Mensalidade)'), ('PLANO_CONTAS_JUROS_ID', 'Financeiro - ID Plano Contas (Juros/Multa)'), ('PLANO_CONTAS_SERVICOS_ID', 'Serviços - ID Plano Contas (Receita de Serviços)')], max_length=100),
        ),
    ]
