# Generated by Django 5.2.8 on 2026-07-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parametrosistema_chave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrosistema',
            options={'permissions': [('acesso_modulo', 'Acesso ao módulo Configurações')], 'verbose_name': 'Parâmetro do Sistema', 'verbose_name_plural': 'Parâmetros do Sistema'},
        ),
    ]
