# Generated by Django 5.2.8 on 2026-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'permissions': [('acesso_modulo', 'Acesso ao módulo Painel')],
                'managed': False,
            },
        ),
    ]
