# Generated by Django 5.2.8 on 2026-07-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_planodecontas_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planodecontas',
            options={'ordering': ['codigo', 'nome'], 'permissions': [('acesso_modulo', 'Acesso ao módulo Financeiro')], 'verbose_name': 'Plano de Contas', 'verbose_name_plural': 'Planos de Contas'},
        ),
    ]
