# Generated by Django 5.2.8 on 2026-06-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cadastro_rg_ie_cadastro_inscricao_estadual_and_more'),
        ('core', '0004_alter_parametrosistema_chave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº OS')),
                ('descricao_geral', models.TextField(help_text='Descreva o objeto recebido e o trabalho a ser feito', verbose_name='Descrição do Objeto / Peça')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('data_conclusao', models.DateField(blank=True, editable=False, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluída'), ('FECHADA', 'Fechada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=10)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('A_VISTA', 'À Vista'), ('A_PRAZO', 'A Prazo')], max_length=10, null=True, verbose_name='Forma de Pagamento')),
                ('qtd_parcelas', models.IntegerField(default=1, verbose_name='Quantidade de Parcelas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(help_text='Cliente que enviou a peça / encomenda', on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_entrada', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ServicoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servicos.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Serviço da OS',
                'verbose_name_plural': 'Serviços da OS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('meta_valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta (R$)')),
                ('avaliacao_ruim', models.DecimalField(decimal_places=1, default=50.0, help_text='Ex: 50.0 = Ruim se atingir menos de 50% da meta', max_digits=5, verbose_name='% Mínima para Ruim')),
                ('avaliacao_bom', models.DecimalField(decimal_places=1, default=80.0, help_text='Ex: 80.0 = Bom se atingir entre 50% e 80% da meta', max_digits=5, verbose_name='% Mínima para Bom')),
                ('avaliacao_otimo', models.DecimalField(decimal_places=1, default=100.0, help_text='Ex: 100.0 = Ótimo se atingir 100% ou mais da meta', max_digits=5, verbose_name='% Mínima para Ótimo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Meta do Funcionário',
                'verbose_name_plural': 'Metas dos Funcionários',
                'ordering': ['-ano', '-mes', 'funcionario__nome'],
                'unique_together': {('empresa', 'funcionario', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='FuncionarioOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_remuneracao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Remuneração (R$)')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.funcionario', verbose_name='Funcionário')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='servicos.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Funcionário da OS',
                'verbose_name_plural': 'Funcionários da OS',
                'ordering': ['funcionario__nome'],
                'unique_together': {('ordem_servico', 'funcionario')},
            },
        ),
    ]
