# Generated by Django 5.2.8 on 2026-06-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cadastro_rg_ie_cadastro_inscricao_estadual_and_more'),
        ('core', '0004_alter_parametrosistema_chave'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº Orçamento')),
                ('descricao', models.TextField(help_text='Descreva o serviço proposto', verbose_name='Descrição / Observação do Orçamento')),
                ('data', models.DateField(verbose_name='Data do Orçamento')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Validade do Orçamento')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('A_VISTA', 'À Vista'), ('A_PRAZO', 'A Prazo')], max_length=10, null=True, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(help_text='Cliente para quem o orçamento será enviado', on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ServicoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servicos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Serviço do Orçamento',
                'verbose_name_plural': 'Serviços do Orçamento',
                'ordering': ['id'],
            },
        ),
    ]
