# Generated by Django 5.2.8 on 2026-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parametrosistema_chave'),
        ('servicos', '0003_formapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='numero',
            field=models.CharField(editable=False, max_length=20, verbose_name='Nº Orçamento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='numero',
            field=models.CharField(editable=False, max_length=20, verbose_name='Nº OS'),
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='ordemservico',
            unique_together={('empresa', 'numero')},
        ),
    ]
