# Generated by Django 5.2.8 on 2026-06-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parametrosistema_chave'),
        ('servicos', '0004_alter_orcamento_numero_alter_ordemservico_numero_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='funcionario',
            unique_together={('empresa', 'nome')},
        ),
    ]
