# Generated by Django 5.2.8 on 2026-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_alter_formapagamento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metafuncionario',
            name='avaliacao_bom',
        ),
        migrations.RemoveField(
            model_name='metafuncionario',
            name='avaliacao_otimo',
        ),
        migrations.RemoveField(
            model_name='metafuncionario',
            name='avaliacao_ruim',
        ),
        migrations.AddField(
            model_name='metafuncionario',
            name='bonus_bom',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Valor fixo pago quando atingir faixa Bom', max_digits=10, verbose_name='Bônus Bom (R$)'),
        ),
        migrations.AddField(
            model_name='metafuncionario',
            name='bonus_excelente_percentual',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Percentual sobre o valor acima da meta. Ex: 5.0 = 5% sobre R$ acima da meta', max_digits=5, verbose_name='Bônus Excelente (%)'),
        ),
        migrations.AddField(
            model_name='metafuncionario',
            name='bonus_otimo',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Valor fixo pago quando atingir faixa Ótimo', max_digits=10, verbose_name='Bônus Ótimo (R$)'),
        ),
        migrations.AddField(
            model_name='metafuncionario',
            name='percentual_bom',
            field=models.DecimalField(decimal_places=1, default=120.0, help_text='Ex: 120.0 = Bom de 101% até 120%', max_digits=6, verbose_name='% Limite Superior Bom'),
        ),
        migrations.AddField(
            model_name='metafuncionario',
            name='percentual_otimo',
            field=models.DecimalField(decimal_places=1, default=140.0, help_text='Ex: 140.0 = Ótimo de 121% até 140%', max_digits=6, verbose_name='% Limite Superior Ótimo'),
        ),
        migrations.AddField(
            model_name='metafuncionario',
            name='percentual_regular',
            field=models.DecimalField(decimal_places=1, default=100.0, help_text='Ex: 100.0 = Regular de 91% até 100%', max_digits=6, verbose_name='% Limite Superior Regular'),
        ),
        migrations.AddField(
            model_name='metafuncionario',
            name='percentual_ruim',
            field=models.DecimalField(decimal_places=1, default=90.0, help_text='Abaixo deste valor = Muito Baixo. Ex: 90.0 = Ruim até 90%', max_digits=6, verbose_name='% Limite Superior Ruim'),
        ),
    ]
