# Generated by Django 5.2.8 on 2026-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_remove_metafuncionario_avaliacao_bom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado ao valor total dos serviços', max_digits=12, verbose_name='Desconto (R$)'),
        ),
    ]
