# Generated by Django 5.2.8 on 2026-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_ordemservico_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='assinatura_cliente_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura do Cliente (Base64)'),
        ),
    ]
