# Generated by Django 5.2.8 on 2026-07-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_ordemservico_assinatura_cliente_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='assinatura_cliente_base64',
        ),
    ]
