# Generated by Django 5.2.8 on 2026-07-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_remove_ordemservico_assinatura_cliente_base64'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'permissions': [('acesso_modulo', 'Acesso ao módulo Serviços')], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
