# Generated by Django 5.2.4 on 2026-10-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_categoriacliente_options'),
        ('servicos', '0011_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente_avulso',
            field=models.CharField(blank=True, default='', help_text='Nome do cliente sem cadastro (opcional)', max_length=255, verbose_name='Cliente Avulso'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente_avulso',
            field=models.CharField(blank=True, default='', help_text='Nome do cliente sem cadastro (opcional)', max_length=255, verbose_name='Cliente Avulso'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cadastro',
            field=models.ForeignKey(blank=True, help_text='Cliente para quem o orçamento será enviado', null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cadastro',
            field=models.ForeignKey(blank=True, help_text='Cliente que enviou a peça / encomenda', null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Cliente'),
        ),
    ]
