# Generated by Django 5.2.4 on 2026-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0012_orcamento_cliente_avulso_ordemservico_cliente_avulso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado ao valor total dos serviços', max_digits=12, verbose_name='Desconto (R$)'),
        ),
    ]
